# Generated by Django 3.2.16 on 2023-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='student status'),
        ),
    ]
