# Generated by Django 3.2.16 on 2023-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230226_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('UNDER REVIEW', 'UNDER REVIEW'), ('REJECTED', 'REJECTED')], default='UNDER REVIEW', max_length=100)),
            ],
        ),
    ]
